index:
    path: /
    methods: [GET]
    defaults: { _controller: 'App\Controller\DefaultController::indexAction' }

company_update_prices:
    path: /company/{companyId}/update-prices/{companyMarketType?}
    defaults: { _controller: 'App\Controller\CompanyController::updatePricesAction' }
    methods: [GET, POST]

company_create:
    path: /company/create
    defaults: { _controller: 'App\Controller\CompanyController::createCompanyAction' }
    methods: [GET, POST]
